### ISSUE TITLE
Incorrect issue for gaunt2.zip Gauntlet II.mra 

### ISSUE THREAD

**Issue by Vampier** [MiSTer-devel/Arcade_Gauntlet_MiSTer#1]
First of all - thanks for the great Gauntlet 2 core, it's a lot of fun to play with multiple players.

There is a small issue with an MRA file: When the MD5 in Gauntlet II.mra was created the actual MD5 of the file was used. 

`md5sum Gauntlet\ II.mra 
ed8d5138c9a57f79189748db49724c27  Gauntlet II.mra`

The correct MD5 of the file is **0847AC69B06DD977B64CDA3677367FE1**

https://github.com/MiSTer-devel/Arcade_Gauntlet_MiSTer/commit/5121c6f1c7269e8a458597f94c5a636635970c12

The commit here is incorrect as I cannot find any file related to gaunt2.zip with the MD5 of 565342714f24b2ed4d61880f12711926

**Comment by d18c7db** [comment]
Yeah, thanks. I removed checksums for now.
