### ISSUE TITLE
Vindicators Part II - 2 Player Controller is Semi-Controlled by Player 1

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Arcade_Gauntlet_MiSTer#2]
When playing in 2 player mode, when Player 1 moves back and forward so does Player 2, but Player 2 can move sideways and fire independently. Essentially, Player 1 controls half of Player 2's movements and I just wanted to address the issue 👍

**Comment by d18c7db** [comment]
What controllers are you using? Are both players using joysticks or is there a keyboard involved too?

**Comment by d18c7db** [comment]
Nevermind, I saw the issue, typo in code reused some of the P1 controls for P2.
