### ISSUE TITLE
Gauntlet II texts are missing

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Arcade_Gauntlet_MiSTer#3]
I hope that at some point the missing text in the pop-ups etc will be fixed :)

**Comment by d18c7db** [comment]
Can you attach a picture so I can see. Not aware of any missing text.

On 23/01/2021, at 10:42, dfilskov <notifications@github.com<mailto:notifications@github.com>> wrote:


I hope that at some point the missing text in the pop-ups etc will be fixed :)

**Comment by dfilskov** [comment]
Sure - you can't miss it.

![20210124_201838-screen](https://user-images.githubusercontent.com/15096058/105646098-39a6ab80-5e9e-11eb-8bc2-9fb6ea27e6f0.png) ![20210124_201847-screen](https://user-images.githubusercontent.com/15096058/105646099-39a6ab80-5e9e-11eb-9c35-f5e3877c2dad.png)

![20210124_201902-screen](https://user-images.githubusercontent.com/15096058/105646100-3a3f4200-5e9e-11eb-8d9e-b2737ba78086.png) ![20210124_201911-screen](https://user-images.githubusercontent.com/15096058/105646101-3a3f4200-5e9e-11eb-9764-2556c363df86.png)

**Comment by dfilskov** [comment]
Wait ... I found a different ROM and now it works!
