### ISSUE TITLE
(EDIT ... no bug - my mistake, sorry!) GAUNT2 video info says 336:240 but it's not

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Arcade_Gauntlet_MiSTer#4]
I've tested this by tuning vscale_border and custom aspect ratio to make the signal match the pixels on my flatpanel and at integers of 336 and 256 exactly/perfectly even though the video info says otherwise and even screenshots are saved as 336x240. Quite confusing :)

**Comment by d18c7db** [comment]
I’m not sure what you want me to do with this.

On 15/02/2021, at 21:37, dfilskov <notifications@github.com<mailto:notifications@github.com>> wrote:


I've tested this but tuning vscale_border and custom aspect ratio to the match the pixels on my flatpanel and at integers of 336 and 256 it matches the pixels exactly/perfectly even though the video info says otherwise and even screenshots are saved as 336x240. Quite confusing :)

**Comment by dfilskov** [comment]
I thought perhaps you simply write in a string what resolution was to be shown and that could be adjusted since there's nothing wrong with the core otherwise ... I figured it must be a text string simply.

Do you think it's actually a bug in the MiSTer framework? - I'll create an issue in that repo if that's more likely.

**Comment by sorgelig** [comment]
screenshot is the memory dump of frame buffer. If it's 336x240 then video is really 336x240

**Comment by dfilskov** [comment]
I see. Thanks. Do you know why then it's shown as 336x256 on the screen? - I tested this by using integer scaling and found the perfect scaling for both Gauntlet 1 and Gauntlet 2 - they both have the same video info and screenshot size 336x240 but to make them become perfect integer scaling they need to be treated as 336x256:

On a 1920x1080 display these should the working hor./vert. integer settings (for 256 height):

[GAUNTLET] ;  336 x 256 (video info says 240)
vscale_border=28
custom_aspect_ratio_1=1344:1024
custom_aspect_ratio_2=1344:768

[GAUNT2] ;  336 x 256 (video info says 240)
vscale_border=28
custom_aspect_ratio_1=1344:1024
custom_aspect_ratio_2=1344:768

If the core height was indeed 240 the integer settings would look like this:

[GAUNTLET] ; 336 x 240
vscale_border=60
custom_aspect_ratio_1=1344:960
custom_aspect_ratio_2=1344:720

... but I'm quite sure the lower one doesn't give hor./vert. integer scaling.

**Comment by sorgelig** [comment]
if you are still using your square 1920x1920 monitor, then problem may come from the way your monitor shows non-native resolutions.

**Comment by dfilskov** [comment]
Let me test on a 1920x1080, 1280x1024 and another monitor and get back.

**Comment by d18c7db** [comment]
Gauntlet outputs 336x240 analog RGBI video which is derived by hardware dividers from the main clock and is faithful to the schematic. What happens after that video signal enters the MiSTer sys scandoublers/filters/HDMI encoders...etc... and then interpreted by your monitor is a little beyond the scope of this Atari hardware implementation and maybe belongs as an issue here https://github.com/MiSTer-devel/Template_MiSTer. Closing this.

**Comment by dfilskov** [comment]
It's not my monitor that interprets that the original resolution of the core is 336x240 instead of 448x256 - it's the MiSTer system, I guess (I thought it was a bug in the core since most other systems show the correct original resolution but perhaps it's in the MiSTer system then). I'll move the issue to the path you suggested if the issue is still there :)

Btw I checked my MiSTer.ini and see now that I'm using integers of 448x256 - not 336x240 - to make the image interger scaled correctly.

**Comment by dfilskov** [comment]
It was my mistake, sorry!!

For GAUNTLET - to get integer scaling - I had added this to the MiSTer.ini by mistake:

 [GAUNTLET] ; 336:256 (video info says 240)
video_mode=1920,16,8,16,1920,16,8,16,230500
vscale_border=120
custom_aspect_ratio_1=1792:1280
custom_aspect_ratio_2=1792:1536

... but it should have been

[GAUNTLET] ; 336:240
video_mode=1920,16,8,16,1920,16,8,16,230500
vscale_border=120
custom_aspect_ratio_1=1680:1200
custom_aspect_ratio_2=1680:1440 ; too tall

or simply

[GAUNTLET] ; 336:240
vscale_border=120
custom_aspect_ratio_1=1680:1200

(my display is square: 1920x1920 but set to 1920x1440 as standard in MiSTer.ini)

Sorry for the confusion!
