### ISSUE TITLE
_alternatives in MiSTer-devel/MRA-Alternatives

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-devel/Arcade_Gauntlet_MiSTer#6]
Hey, I pushed your Alternatives here:

https://github.com/MiSTer-devel/MRA-Alternatives_MiSTer/tree/master/_alternatives/_Vindicators%20part%20II
https://github.com/MiSTer-devel/MRA-Alternatives_MiSTer/tree/master/_alternatives/_Gauntlet
https://github.com/MiSTer-devel/MRA-Alternatives_MiSTer/tree/master/_alternatives/_Gauntlet%20II

Since that repository is already hosting all the alternatives, and could be confusing for contributors to have the same MRAs in two places, would you consider deleting the _alternatives folder from this repository?

Thanks!

**Comment by d18c7db** [comment]
Done
