### ISSUE TITLE
Super Sprint on this core?

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Arcade_Gauntlet_MiSTer#7]
Isn't Super Sprint using the same platform as Gauntlet? - perhaps it would be managable to get that up'n'running?
https://upload.wikimedia.org/wikipedia/en/7/75/ARC_Super_Sprint.png
https://en.wikipedia.org/wiki/Super_Sprint

Or doesn't only require an MRA and the ROM?

**Comment by d18c7db** [comment]
According to the schematic the Super Sprint uses a T11 CPU not a 68010, so that alone is a showstopper.

**Comment by dfilskov** [comment]
Oh - that' too bad. I wonder why they use the same coin sound as the other games on this core - sort of a tubular bell.
